// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sacramentplanner.Models;

#nullable disable

namespace sacramentplanner.Migrations
{
    [DbContext(typeof(SacramentPlannerContext))]
    [Migration("20220714211949_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("sacramentplanner.Models.Bishopric", b =>
                {
                    b.Property<int>("BishopricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BishopName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstCounselorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondCounselorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.HasKey("BishopricId");

                    b.ToTable("Bishopric", (string)null);
                });

            modelBuilder.Entity("sacramentplanner.Models.Hymn", b =>
                {
                    b.Property<int>("HymnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HymnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HymnNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HymnId");

                    b.ToTable("Hymn", (string)null);
                });

            modelBuilder.Entity("sacramentplanner.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("sacramentplanner.Models.SacramentPlan", b =>
                {
                    b.Property<int>("SacramentPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Benediction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosingHymnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClosingHymnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conducting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Invocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsFastSunday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningHymnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpeningHymnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Presiding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SacramentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SacramentHymnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SacramentHymnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("SacramentPlanId");

                    b.ToTable("SacramentPlan", (string)null);
                });

            modelBuilder.Entity("sacramentplanner.Models.Talk", b =>
                {
                    b.Property<int>("TalkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SacramentPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TalkId");

                    b.HasIndex("SacramentPlanId");

                    b.ToTable("Talk", (string)null);
                });

            modelBuilder.Entity("sacramentplanner.Models.Talk", b =>
                {
                    b.HasOne("sacramentplanner.Models.SacramentPlan", "SacramentPlan")
                        .WithMany("Talks")
                        .HasForeignKey("SacramentPlanId");

                    b.Navigation("SacramentPlan");
                });

            modelBuilder.Entity("sacramentplanner.Models.SacramentPlan", b =>
                {
                    b.Navigation("Talks");
                });
#pragma warning restore 612, 618
        }
    }
}
